{% set name = "exprtk" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArashPartow/exprtk/archive/refs/tags/0.0.2.tar.gz
  sha256: 7e8de4a0bfc9855c1316d8b8bc422061aef9a307c2f42d2e66298980463195c1

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x' ) }}

test:
  commands:
    - test -f $PREFIX/include/exprtk.hpp  # [unix]
    - if not exist %PREFIX%\\Library\\include\\exprtk.hpp exit 1  # [win]

about:
  home: https://www.partow.net/programming/exprtk/index.html
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: C++ Mathematical Expression Parsing And Evaluation Library

extra:
  recipe-maintainers:
    - wolfv
    - marimeireles
    - SylvainCorlay
    - ArashPartow
