{% set name = "exprtk" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArashPartow/exprtk/archive/refs/tags/0.0.3.tar.gz
  sha256: 6c412af7862acdfea74c092e71d33cfc32e8aa361fe535affc86665bf21acef6

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x' ) }}

test:
  commands:
    - test -f $PREFIX/include/exprtk.hpp  # [unix]
    - if not exist %PREFIX%\\Library\\include\\exprtk.hpp exit 1  # [win]

about:
  home: https://www.partow.net/programming/exprtk/index.html
  license: MIT
  license_family: MIT
  license_file: license.txt
  summary: C++ Mathematical Expression Parsing And Evaluation Library
  description: |
    The C++ Mathematical Expression Toolkit Library (ExprTk) is a
    versatile, simple to use, easy to integrate and extremely efficient
    runtime mathematical expression parser and evaluation engine. ExprTk
    supports numerous forms of functional, logical and vector processing
    semantics and is very easily extendible.
  doc_url: https://www.partow.net/programming/exprtk/readme.html

extra:
  recipe-maintainers:
    - wolfv
    - marimeireles
    - SylvainCorlay
    - ArashPartow
