{% set name = "exprtk" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArashPartow/exprtk/archive/refs/tags/0.0.1.tar.gz
  sha256: fb72791c88ae3b3426e14fdad630027715682584daf56b973569718c56e33f28

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x' ) }}

test:
  commands:
    - test -f $PREFIX/include/exprtk.hpp  # [unix]
    - if not exist %PREFIX%\\Library\\include\\exprtk.hpp exit 1  # [win]

about:
  home: https://www.partow.net/programming/exprtk/index.html
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: C++ Mathematical Expression Parsing And Evaluation Library

extra:
  recipe-maintainers:
    - wolfv
    - marimeireles
    - SylvainCorlay
    - ArashPartow
